# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "1.100.0"
default_platform :ios

platform :ios do
  before_all do
    xcversion(version: '~> 9.0')
    #unlock_keychain(path: 'login.keychain') if is_ci
    SLATHER_IGNORES = %w(../* */AppDelegate.swift */Constants/* */Coordinators/*).freeze
    XCARGS = "APP_ENVIRONMENT=#{ENV['APP_ENVIRONMENT']}"
  end
  
  desc "Run the tests and generate HTML coverage reports"
  lane :test_report do
    scan(
      scheme: ENV['SCHEME'],
      xcargs: XCARGS,
      output_directory: './Reports/TU',
      output_types: "html",
      open_report: true,
      code_coverage:true
    )
    slather(
      workspace: ENV['XCWORKSPACE'],
      proj: ENV['XCPROJECT'],
      scheme: ENV['SCHEME'],
      ignore: SLATHER_IGNORES,
      source_directory: 'DMSpaceX',
      output_directory: './Reports/Coverage',
      html: true,
      show: true
    )
  end
  
  desc "Build the app target"
  lane :build do
    xcbuild(
      scheme: ENV['SCHEME'],
      xcargs: XCARGS,
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
